version: '3.9'
services:
    mongo:
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: rasa
            MONGO_INITDB_ROOT_PASSWORD: rasa
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: rasa
            ME_CONFIG_MONGODB_ADMINPASSWORD: rasa