version: '3.9'
services:
    mongo:
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: rasa
            MONGO_INITDB_ROOT_PASSWORD: rasa
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: rasa
            ME_CONFIG_MONGODB_ADMINPASSWORD: rasa
        depends_on:
            - mongo
    rasa-actions-server:
        build: ./rasa_actions_server
        ports:
            - 5055:5055
        depends_on:
            - mongo
        links:
            - "mongo"
    rasa-nlu-server:
        image: rasa/rasa:2.5.1
        ports:
            - 5005:5005
        volumes:
            - ./rasa_nlu:/app
        links:
            - "mongo"
            - "rasa-actions-server"
        command: >
            run
            --enable-api
            --cors ['http://localhost:8000']
        depends_on:
            - mongo
            - rasa-actions-server
    front:
        build: ./front
        depends_on:
            - rasa-nlu-server
        ports:
            - 8000:8000